DROP TABLE USERS;
CREATE TABLE USERS (
	
	ID			NUMBER(10,0)	NOT NULL AUTO_INCREMENT,
	USERNAME	VARCHAR2(255)	NOT NULL,
	PASSWORD	VARCHAR2(255)	NOT NULL,
	ROLE		VARCHAR2(255)	NOT NULL,

	PRIMARY KEY (ID)
);

DROP SEQUENCE USER_ID_SEQ;
CREATE SEQUENCE USER_ID_SEQ
 START WITH 3
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;

DROP TABLE PROJECT;
CREATE TABLE PROJECT (
	
	ID			NUMBER(10,0)	NOT NULL AUTO_INCREMENT,
	NAME		VARCHAR2(255)	NOT NULL,
	DESCRIPTION	VARCHAR2(255)	DEFAULT NULL,

	PRIMARY KEY (ID)
);

DROP SEQUENCE PROJECT_ID_SEQ;
CREATE SEQUENCE PROJECT_ID_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;

